language: node_js
node_js: "6"
os:
- linux

dist: trusty

sudo: false

cache:
  directories:
  - node_modules

addons:
  apt:
    packages:
    - fakeroot
    - rpm

branches:
  only:
  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gnucap -y
  
install:
- npm install
- npm update

git:
  depth: 500

script:
#- cd SpiceSimulation
- buildVersion=$(git rev-list --count HEAD .); 
- echo $buildVersion;
- mkdir out
- echo $buildVersion > out/buildversion.txt; 
#- sed -i -e "s/<buildVersion>/1.0.$buildVersion/" package.json
- gnucap -b main.ckt
- pwd
- ls out
- ls out/*
- find out -iname *.zip
- cd out
- find . -type f -not -name index.html -printf '<a href="%p">%p</a><br/>' >> index.html

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: out
  on:
    branch: master
